In [ ]:
#Numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#Checking NumPy Version
print(np.__version__)

2.1.3


In [ ]:

#Creating a NumPy ndarray Object


In [7]:
#!D Array 
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#2D Array

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
#3D Array 

arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [11]:
# Check how many dimension the array have 

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:

#Access Array Elements


In [12]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])


1
2
3
4


In [ ]:
# Example
#Get third and fourth elements from the following array and add them.

In [13]:
print(arr[2] +arr[3])

7


In [ ]:

#Access 2-D Arrays


In [15]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row : ',arr[0,1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row :  2
5th element on 2nd row:  10


In [ ]:

#Access 3-D Arrays


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:

#Example

#Print the last element from the 2nd dim:

In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
