In [ ]:

#NumPy Array Slicing


In [4]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
#Slice elements from index 1 to index 5 from the following array:

print(arr[1:5])

[2 3 4 5]


In [5]:
#Slice elements from index 4 to the end of the array:

print(arr[4:])

[5]


In [6]:
#Slice elements from the beginning to index 4 (not included):

print(arr[:4])

[1 2 3 4]


In [ ]:

#Negative Slicing


In [7]:
print(arr[-3:-1])

[3 4]


In [ ]:

# 1D ARRAY SLICING


In [8]:
import numpy as np

In [9]:
a = np.arange(10)   # [0 1 2 3 4 5 6 7 8 9]
print("1D Array:", a)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [10]:
# Q1: First 5 elements
print("First 5:", a[:5])   # [0 1 2 3 4]

First 5: [0 1 2 3 4]


In [11]:
# Q2: Last 4 elements

print("Last 4:", a[-4:])   # [6 7 8 9]

Last 4: [6 7 8 9]


In [12]:
# Q3: Elements from index 2 to 7

print("Index 2 to 6: ",a[2:7])

Index 2 to 6:  [2 3 4 5 6]


In [13]:
# Q4: Reverse the array

print("Revered Array is :" ,a[::-1])

Revered Array is : [9 8 7 6 5 4 3 2 1 0]


In [14]:
# Q5: Every 2nd elementa

print("step 2: ", a[::2])

step 2:  [0 2 4 6 8]


In [15]:
# Q6: Middle part

print("middle part :" ,a[4:7])

middle part : [4 5 6]


In [7]:
ar = np.arange(15)   
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
# Slice with negative step (reverse with step)
print(ar[::-2]) 

[14 12 10  8  6  4  2  0]


In [14]:
# From index 3 to 10, every 3rd element
print(ar[3:11:3])

[3 6 9]


In [15]:
# Fancy slicing (specific indices)
print(ar[[0, 4, 7, 10]])

[ 0  4  7 10]


In [ ]:

# 2D ARRAY SLICING



In [21]:
b=np.arange(1,13).reshape(3,4)

In [30]:
print("  \n 2D Array ia \n ",b)

  
 2D Array ia 
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# Q1: First row

print("First Row is ", b[0,: ])

First Row is  [1 2 3 4]


In [24]:
# Q2: Last Row
print("Last row is " ,b[2,: ])

Last row is  [ 9 10 11 12]


In [25]:
# Q3 First column
print("First column is ", b[:,0])

First column is  [1 5 9]


In [28]:
# Q4: Last column
print("last colums is ",b[ :,3])

last colums is  [ 4  8 12]


In [ ]:
# Q5 Sub-matrix (first 2 rows & 2 cols)

print("top -left 2*2 \n " , b[